-- Migration: 21_rate_limiting
-- Creates a table and RPC for distributed rate limiting across Edge Functions

BEGIN;

CREATE TABLE IF NOT EXISTS public.api_rate_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    request_count INT NOT NULL DEFAULT 1,
    window_start_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(ip_address, endpoint)
);

-- Enable RLS (Service Role only)
ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service Role Only" ON public.api_rate_limits FOR ALL USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION check_rate_limit(
    p_ip TEXT,
    p_endpoint TEXT,
    p_max_reqs INT,
    p_window_seconds INT
) RETURNS BOOLEAN AS $$
DECLARE
    v_window_start TIMESTAMPTZ;
    v_req_count INT;
BEGIN
    -- Cleanup old records probabilistically or just rely on the window check
    -- We do a direct upsert for performance

    INSERT INTO public.api_rate_limits (ip_address, endpoint, request_count, window_start_at)
    VALUES (p_ip, p_endpoint, 1, NOW())
    ON CONFLICT (ip_address, endpoint) DO UPDATE
    SET 
        request_count = CASE 
            WHEN public.api_rate_limits.window_start_at < NOW() - (p_window_seconds || ' seconds')::INTERVAL THEN 1
            ELSE public.api_rate_limits.request_count + 1
        END,
        window_start_at = CASE 
            WHEN public.api_rate_limits.window_start_at < NOW() - (p_window_seconds || ' seconds')::INTERVAL THEN NOW()
            ELSE public.api_rate_limits.window_start_at
        END
    RETURNING request_count, window_start_at INTO v_req_count, v_window_start;

    IF v_req_count > p_max_reqs THEN
        RETURN FALSE;
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMIT;
