from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Dict


def create_post(
    venue_id: str | None = None,
    media_type: str = "image",
    media_url: str = "",
    caption: str | None = None,
    ttl_hours: int = 24,
    author_alias: str | None = None,
    is_user_post: bool = False,
    hashtag: str | None = None,
) -> Dict[str, Any]:
    """
    Build a new post row for insertion into Supabase.
    Primary key is generated by Supabase.
    """
    now = datetime.utcnow()
    expires_at = now + timedelta(hours=ttl_hours)
    return {
        "venue_id": venue_id,
        "media_type": media_type,
        "media_url": media_url,
        "caption": caption,
        "created_at": now.isoformat(),
        "expires_at": expires_at.isoformat(),
        "author_alias": author_alias,
        "is_user_post": is_user_post,
        "hashtag": hashtag,
        "metrics": {
            "views": 0,
            "likes": 0,
        },
    }


def post_to_dict(doc: Dict[str, Any]) -> Dict[str, Any]:
    """
    Map a Supabase `posts` row to the public API payload.
    """
    return {
        "id": str(doc.get("id")),
        "venue_id": str(doc.get("venue_id")) if doc.get("venue_id") else None,
        "media_type": doc.get("media_type"),
        "media_url": doc.get("media_url"),
        "caption": doc.get("caption"),
        "created_at": doc.get("created_at"),
        "expires_at": doc.get("expires_at"),
        "author_alias": doc.get("author_alias"),
        "is_user_post": doc.get("is_user_post", False),
        "hashtag": doc.get("hashtag"),
        "metrics": doc.get("metrics", {}),
        "is_liked": doc.get("is_liked", False),
    }


