from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional


def create_venue(
    owner_id: str,
    name: str,
    venue_type: str,
    city: str,
    area: str,
    contact_phone: str,
    categories: Optional[List[str]] = None,
    images: Optional[List[str]] = None,
    address: Optional[str] = None,
    lat: Optional[float] = None,
    lng: Optional[float] = None,
) -> Dict[str, Any]:
    """
    Build a new venue row for insertion into Supabase.
    Primary key is generated by Supabase.
    """
    now = datetime.utcnow()
    return {
        "owner_id": owner_id,
        "name": name,
        "type": venue_type,
        "city": city,
        "area": area,
        "contact_phone": contact_phone,
        "categories": categories or [],
        "images": images or [],
        "address": address,
        # "lat": lat,  # Column missing in DB
        # "lng": lng,  # Column missing in DB
        "created_at": now.isoformat(),
        "updated_at": now.isoformat(),
    }


def venue_to_dict(doc: Dict[str, Any]) -> Dict[str, Any]:
    """
    Map a Supabase `venues` row to the public API payload.
    """
    return {
        "id": str(doc.get("id")),
        "owner_id": str(doc.get("owner_id")) if doc.get("owner_id") else None,
        "name": doc.get("name"),
        "type": doc.get("type"),
        "city": doc.get("city"),
        "area": doc.get("area"),
        "contact_phone": doc.get("contact_phone"),
        "categories": doc.get("categories", []),
        "images": doc.get("images", []),
        "address": doc.get("address"),
        "lat": doc.get("lat"),
        "lng": doc.get("lng"),
        "created_at": doc.get("created_at"),
        "updated_at": doc.get("updated_at"),
        "metrics": doc.get("metrics", {"likes": 0, "views": 0}),
        "working_hours": doc.get("working_hours"),
    }


